name: Update foF2 Map

on:
  schedule:
    - cron: '0 * * * *'  # 每小時執行一次 UTC
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download foF2 image
        run: |
          mkdir -p images
          curl -o images/fof2.png https://prop.kc2g.com/images/fof2.png

      - name: Commit and push if image changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add images/fof2.png
          git diff --cached --quiet || git commit -m "Auto update foF2 map"
          git push

