name: Update foF2 Map

on:
  schedule:
    - cron: '0 * * * *'  # 每小時執行一次（UTC 時間）
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create images folder
        run: mkdir -p images

      - name: Download foF2 image
        run: |
          curl -sSL --retry 5 --connect-timeout 10 -o images/fof2.png https://prop.kc
